### ISSUE TITLE
WA and UA

### ISSUE THREAD

**Issue by SunshlnW** [david-yoon/attentive-modality-hopping-for-SER#1]
I've searched these two terms in many websites, the bloggers exlain it always like this:"The weighted accuracy (WA) corresponds to the correctly detected samples divided by the total number of samples. The unweighted accuracy (UA) is given by the averaged recall of the two classes of a label dimension. ", while you calculate the WA and UA using the precision_score.And you reverse the output of backward lstm，I don't understand this!

**Comment by david-yoon** [comment]
Hi,
I checked the code and found that the misuse of the metric, as you pointed out. Thank you for your correction. When I change the metric from precision to accuracy, I find that the model performance is similar for the weighted case. However, the model performance is lower for the unweighted case (i.e., AMH (precision) 0.624/0.597 -> AMH (accuracy) 0.618/0.547)). This behavior is similarly observed for other models (MHA, MDRE).  I'll report the results for both metrics and update the paper. The revised codes are available from the GitHub.
