### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by SteveTanggithub** [david-yoon/attentive-modality-hopping-for-SER#2]
I got error when runing like below:
![image](https://user-images.githubusercontent.com/62332133/89713176-b2857a00-d9c8-11ea-8776-58e41bef398f.png)
![image](https://user-images.githubusercontent.com/62332133/89713185-bca77880-d9c8-11ea-9e5f-bdb20ebd6f3b.png)

**Comment by SteveTanggithub** [comment]
I use the data u provide,and didn't change anything

**Comment by david-yoon** [comment]
Hi,
I clone the GitHub and download the released dataset. In my case, I can successfully train the model.
In your case, it seems that the exception occurs in the training step. 

I put the "print" code to print the exception. Please pull the code and try it again. It will provide detailed information on where the error occurs.

> except Exception as e:
                print ("excepetion occurs in train step", e)
                pass
